# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "chef/centos-7.0"
  config.vm.provision "shell", path: "provision.sh" 
  config.vm.network "forwarded_port", guest: 8082, host: 8000
end
