# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "chef/centos-7.0"
  config.vm.network "forwarded_port", guest: 8082, host: 8000
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/server.yml"
	ansible.verbose = "vvvv"
  end
end