---
- name: Install necessary OS programs
  yum: name={{ item }} state=installed
  with_items:
    - autoconf
    - automake
    - binutils
    - bison
    - flex
    - gcc
    - gcc-c++
    - gettext
    - libtool
    - make
    - patch
    - pkgconfig
    - redhat-rpm-config
    - rpm-build
    - rpm-sign
    - gettext-devel 
    - openssl-devel 
    - perl-CPAN 
    - perl-devel 
    - zlib-devel
    - git
- name: Install nvm
  sudo: no
  shell: "curl https://raw.githubusercontent.com/creationix/nvm/v{{ nvm.version }}/install.sh | bash"
  tags: nvm

- name: Update .bashrc
  sudo: no
  lineinfile: >
    dest="/home/{{ env.user }}/.bashrc"
    line="source /home/{{ env.user }}/.nvm/nvm.sh"
  tags: nvm
  
- name: Install and alias node
  sudo: no
  shell: "/bin/bash -c 'source /home/{{ env.user }}/.nvm/nvm.sh && nvm install {{ nvm.node_version }} && nvm alias default {{ nvm.node_version }}'"
  tags: nvm
  
- name: Install pm2
  sudo: no
  shell: "npm install pm2 -g"
  
- name: Clone express-webhook
  sudo: no
  shell: "cd /home/{{ env.user }} && git clone {{ build.repo_path }}/{{ build.repo_name }}"
  
- name: Enter express-webhook, install, and start with pm2
  sudo: no
  shell: "cd {{ build.repo_name }} && npm i && pm2 start server.js"